# Generated by Django 3.1.3 on 2020-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0002_auto_20201106_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(default='/media/default_image.jpg', upload_to='images/'),
        ),
    ]
