# Generated by Django 3.1.3 on 2020-11-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0004_auto_20201107_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vote_answer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vote_question',
        ),
    ]
