# Generated by Django 3.1.3 on 2020-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0006_auto_20201107_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
