# Generated by Django 3.1.3 on 2020-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0007_auto_20201107_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_answer',
            field=models.ManyToManyField(related_name='answer_voted', to='asktheexperts.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_question',
            field=models.ManyToManyField(related_name='question_voted', to='asktheexperts.Question'),
        ),
    ]
