# Generated by Django 3.1.3 on 2020-11-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0009_auto_20201114_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='score',
        ),
    ]
