# Generated by Django 3.1.3 on 2020-11-17 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0010_auto_20201117_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vote_answer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vote_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='downvote_answer',
            field=models.ManyToManyField(related_name='answer_downvoted', to='asktheexperts.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvote_question',
            field=models.ManyToManyField(related_name='question_downvoted', to='asktheexperts.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='upvote_answer',
            field=models.ManyToManyField(related_name='answer_upvoted', to='asktheexperts.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvote_question',
            field=models.ManyToManyField(related_name='question_upvoted', to='asktheexperts.Question'),
        ),
    ]
