# Generated by Django 3.1.3 on 2020-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0011_auto_20201117_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
