# Generated by Django 3.1.3 on 2020-11-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0013_reported_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported_user',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
