# Generated by Django 3.1.3 on 2020-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0014_auto_20201128_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reported_user',
            old_name='reported_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='reported_user',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
