# Generated by Django 3.1.3 on 2020-11-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asktheexperts', '0015_auto_20201128_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
